project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About"
        file: about.qmd
      - text: "CV"
        file: cv.qmd
      - section: "Projects"
        contents:
        - text: "Work-related"
          file: visuals.qmd
        - text: "Work-aside"
          file: side.qmd

format:
  html:
    css: styles.css
    toc: true

execute:
  freeze: auto



